### ISSUE TITLE
Walk-through of a Substrate/FRAME app

### ISSUE THREAD

**Issue by Are10** [sacha-l/substrate-seminar#3]
A beginner/intermediate level talk that goes into what makes up a real-world runtime.
Could include:
* A description of pallets used and why.
* perhaps a bit of code review if that's meaningful.
* Best practices that have been used or not used.

**Comment by Are10** [comment]
I'm still working through the whole backlog of seminars, they really are very helpful.
Thank you for picking these out.

I'll try to identify a more specific topic, my main question at this time is which pallets to use, and why. 
In combination with the ORML, there's quite a few. I've been reading the docs, so I'll get there eventually.

My idea was to go from the "How" you make an app (Substrate/Frame), to "Why" you choose certain pallets.
I will keep going through the backlog and refine this issue (Or create new ones) as I go.

**Comment by sacha-l** [comment]
Hi @Are10 - any new ideas here? If I understand correctly, you're looking to have a seminar for people getting started with using pallet libraries, and outlining the differences between certain pallets who are similar in order to understand why chose one over the over and how to use them? For example FRAME's [uniques pallet](https://docs.substrate.io/rustdocs/latest/pallet_uniques/) vs. ORML's [nft pallet](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/nft#overview).

**Comment by Are10** [comment]
Hi Sacha.
As I am working through all the (excellent) available resources, much of my initial questions have already been resolved.

When I put forward this issue, I was looking for a pallet-centric way of creating a blockchain or parachain application.
"What would be the process of evaluating the envisioned functionality and how to compose that using the different pallets?", "What pallets are available?", and "what is the function of each pallet" and so on. 

I thought it might be helpful to dig into an existing application as an example, with no specific one in mind.
The intent was to get a feel for the "(Conceptual) Anatomy" of a substrate/FRAME based application.

As you mentioned in earlier replies, a lot of these topics have already been covered, so I am questioning the need for a dedicated seminar.

**Comment by sacha-l** [comment]
Sounds good - glad to hear you're finding some good educational resources out there! :) 

I think as you're probably already finding, that the questions you're asking quickly get answered once you dive into writing some functionality for your runtime. Choosing between existing pallets, building your own etc. are all decisions you'll likely make based on your specifications and your target use case.

Here's a good video on using ORML by one of its core contributors by the way (although it uses the older version of FRAME): https://www.youtube.com/watch?v=y1AXitnQSyU

I'll leave this issue open for now in case you have more ideas to add in the context of "getting started with Substrate". We may see fit to combine this topic into another seminar.

**Comment by sacha-l** [comment]
@Are10 - is there any specific ORML pallets you'd be interested in diving into?

**Comment by Are10** [comment]
After discussing with Sasha, I will close this issue in favor of #8.
